# Generated by Django 3.0.3 on 2020-04-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('elements', '0044_remove_textmarkup_targetlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmarkup',
            name='targetlanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language'),
        ),
    ]
