# Generated by Django 3.0.3 on 2020-03-07 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('users', '0005_customuser_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='updated',
            new_name='updatedDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='about',
        ),
        migrations.AddField(
            model_name='profile',
            name='addedDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='learninglanguage',
            field=models.ManyToManyField(blank=True, related_name='user_learning_language', to='categories.Language'),
        ),
        migrations.AddField(
            model_name='profile',
            name='learningtopics',
            field=models.ManyToManyField(blank=True, related_name='user_topics', to='categories.TopicTag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nativelanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_native_language', to='categories.Language'),
        ),
    ]
