# Generated by Django 3.0.3 on 2020-03-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200308_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about',
            new_name='biography',
        ),
    ]
