# Generated by Django 3.0.3 on 2020-03-15 19:12

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200313_1558'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
