# Generated by Django 3.0.3 on 2020-03-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200322_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='geoloc',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
    ]
