# Generated by Django 3.0.3 on 2020-04-11 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_profile_geoloc'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followed',
            field=models.ManyToManyField(blank=True, related_name='profile_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='profile_hidden', to=settings.AUTH_USER_MODEL),
        ),
    ]
