# Generated by Django 3.0.3 on 2021-03-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200411_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='learningtopics',
        ),
    ]
