# Generated by Django 3.0.3 on 2020-05-01 12:20

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('caption', models.CharField(default='', max_length=320)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('event_type', models.CharField(default='Meeting', max_length=140)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(default='', max_length=128, null=True)),
                ('public', models.BooleanField(default=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_curator', to=settings.AUTH_USER_MODEL)),
                ('native_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_native_language', to='categories.Language')),
                ('parent_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence', to='events.CalendarEvent')),
                ('target_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_target_language', to='categories.Language')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_topic', to='categories.TopicTag')),
            ],
        ),
        migrations.CreateModel(
            name='UserInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invite', to='events.CalendarEvent')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_invited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('maybe', models.BooleanField(default=False)),
                ('comment', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='events.CalendarEvent')),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_comment_curator', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='events.CalendarEvent')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrence_attendee', to=settings.AUTH_USER_MODEL)),
                ('event_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='events.CalendarEvent')),
            ],
        ),
    ]
