# Generated by Django 3.0.3 on 2020-05-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventattendee',
            old_name='event_occurrence',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='eventattendee',
            name='attendee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventcomment',
            name='curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_comment_curator', to=settings.AUTH_USER_MODEL),
        ),
    ]
