# Generated by Django 3.0.3 on 2020-05-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200501_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrsvp',
            name='maybe',
        ),
        migrations.AlterField(
            model_name='eventrsvp',
            name='attending',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Maybe', 'Maybe'), ('No', 'No')], default='Yes', max_length=10),
        ),
    ]
