# Generated by Django 3.0.3 on 2020-05-02 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0007_calendarevent_guest_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='guest_list',
            field=models.ManyToManyField(blank=True, related_name='invited_event_guest', to=settings.AUTH_USER_MODEL),
        ),
    ]
