# Generated by Django 3.0.3 on 2020-05-04 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200504_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrsvp',
            name='curationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
