# Generated by Django 3.0.3 on 2020-05-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20200504_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start',
        ),
    ]
