# Generated by Django 3.0.3 on 2020-05-05 12:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200504_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('9a37d5da-8ecb-11ea-85b3-6c4008970758'), max_length=260),
        ),
        migrations.DeleteModel(
            name='UserInvite',
        ),
    ]
