# Generated by Django 3.0.3 on 2020-05-05 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20200505_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('563a2312-f5f6-4c0e-9d0e-1fd95d1bd240'), max_length=260),
        ),
    ]
