# Generated by Django 3.0.3 on 2020-05-12 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200505_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('ff71f6b3-2dbd-474b-99f2-7a5cca094a3d'), max_length=260),
        ),
    ]
