# Generated by Django 3.0.3 on 2020-05-13 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20200512_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f036b211-d9b4-4397-8c57-eca8a7465f12'), max_length=260),
        ),
    ]
