# Generated by Django 3.0.3 on 2020-05-17 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20200513_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('39019f3a-8825-4899-8502-e072f49de5fd'), max_length=260),
        ),
    ]
