# Generated by Django 3.0.3 on 2020-05-17 13:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20200517_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('7100bd8d-9a47-4c1c-b4aa-25d7bf0a82c4'), max_length=260),
        ),
    ]
