# Generated by Django 3.0.3 on 2020-05-17 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20200517_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f81c8407-f574-4b5b-9d79-b355409b318d'), max_length=260),
        ),
    ]
