# Generated by Django 3.0.3 on 2020-05-17 13:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20200517_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('70969371-f7f0-489d-8fb2-9f7393b82df2'), max_length=260),
        ),
    ]
