# Generated by Django 3.0.3 on 2020-05-17 13:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20200517_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('58e8f327-058f-403f-9a45-a35459ee1949'), max_length=260),
        ),
    ]
