# Generated by Django 3.0.3 on 2020-05-17 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_auto_20200517_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('9f137c3d-a679-4bdd-98b7-6aa813087559'), max_length=260),
        ),
    ]
