# Generated by Django 3.0.3 on 2020-05-17 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_auto_20200517_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('3e5346aa-35d2-419c-94cb-7e778ad9a17e'), max_length=260),
        ),
    ]
