# Generated by Django 3.0.3 on 2020-05-17 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20200517_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('aafcabe9-fd19-41f1-91e7-16da1ea9b1f5'), max_length=260),
        ),
    ]
