# Generated by Django 3.0.3 on 2020-05-17 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_auto_20200517_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('371aec1c-117a-439d-9113-ee90bfd105d4'), max_length=260),
        ),
    ]
