# Generated by Django 3.0.3 on 2020-05-17 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_auto_20200517_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('218d011c-e933-4f28-a8de-2c75eca6e73d'), max_length=260),
        ),
    ]
