# Generated by Django 3.0.3 on 2020-05-19 11:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_auto_20200517_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('d6a05a12-f5a2-47dd-8c4d-18482cf41be7'), max_length=260),
        ),
    ]
