# Generated by Django 3.0.3 on 2020-05-21 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_auto_20200519_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('860c3ebb-0368-4a8a-9fb8-b7bf05a31f59'), max_length=260),
        ),
    ]
