# Generated by Django 3.0.3 on 2020-05-22 19:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_auto_20200521_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('6fe1c9b3-6880-413b-8b2e-905ac0d7b058'), max_length=260),
        ),
    ]
