# Generated by Django 3.0.3 on 2020-05-23 18:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_auto_20200522_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('3c069f2c-2e9a-4281-b853-f91af83f46bc'), max_length=260),
        ),
    ]
