# Generated by Django 3.0.3 on 2020-05-24 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_auto_20200523_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('101303c9-c074-4459-91ee-f5b89aedbe8b'), max_length=260),
        ),
    ]
