# Generated by Django 3.0.3 on 2020-05-24 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20200524_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('81d7e390-e6bf-4883-be23-9caedc1de065'), max_length=260),
        ),
    ]
