# Generated by Django 3.0.3 on 2020-05-24 12:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20200524_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('6bd303ba-360b-456a-8a50-ae074ce5ce0d'), max_length=260),
        ),
    ]
