# Generated by Django 3.0.3 on 2020-05-24 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20200524_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('b6e0cef9-6912-48ee-8f5e-9445d45215a8'), max_length=260),
        ),
    ]
