# Generated by Django 3.0.3 on 2020-05-24 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20200524_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('e3fda9af-7f05-4fc6-a09e-57ee61f16f16'), max_length=260),
        ),
    ]
