# Generated by Django 3.0.3 on 2020-05-24 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_auto_20200524_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('714a672f-6c34-4c64-a66e-1b67d5245234'), max_length=260),
        ),
    ]
