# Generated by Django 3.0.3 on 2020-05-24 12:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_auto_20200524_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('8765c1a6-7503-40fa-b4d8-efbddcad6fb7'), max_length=260),
        ),
    ]
