# Generated by Django 3.0.3 on 2020-05-24 14:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_auto_20200524_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f7014d33-5eaa-46b9-950f-556fc8c96b5b'), max_length=260),
        ),
    ]
