# Generated by Django 3.0.3 on 2020-05-24 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_auto_20200524_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('5783c637-7609-41ac-ba3e-5a9d741105d7'), max_length=260),
        ),
    ]
