# Generated by Django 3.0.3 on 2020-05-24 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20200524_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('7621be2e-0fc1-423a-b1fb-889b72fa7df0'), max_length=260),
        ),
    ]
