# Generated by Django 3.0.3 on 2020-05-24 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20200524_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('ad9b862d-e309-4f5f-b9ad-51f5c0279ce3'), max_length=260),
        ),
    ]
