# Generated by Django 3.0.3 on 2020-05-27 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_auto_20200524_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('fa9041c2-ead3-4053-9244-0a05778ef624'), max_length=260),
        ),
    ]
