# Generated by Django 3.0.3 on 2020-05-31 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_auto_20200527_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('d6b04cb5-8cfe-47dd-b617-8baf2ee83ed9'), max_length=260),
        ),
    ]
