# Generated by Django 3.0.3 on 2020-05-31 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20200531_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('fcf7a23f-cedc-48d3-af57-b1523b6f39d1'), max_length=260),
        ),
    ]
