# Generated by Django 3.0.3 on 2020-06-06 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20200606_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2517a470-4420-4c4b-a0b8-27f1aebebc23'), max_length=260),
        ),
    ]
