# Generated by Django 3.0.3 on 2020-06-06 15:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_auto_20200606_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2c220dbf-9443-4109-bfb2-23d5c22134cf'), max_length=260),
        ),
    ]
