# Generated by Django 3.0.3 on 2020-06-06 18:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_auto_20200606_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('000161f8-592f-4f42-b7c3-194147f5cab1'), max_length=260),
        ),
    ]
