# Generated by Django 3.0.3 on 2020-06-06 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_auto_20200606_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('51023cc5-86c2-4281-b32f-d13b14a2e2ab'), max_length=260),
        ),
    ]
