# Generated by Django 3.0.3 on 2021-02-20 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20210220_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('15c2f452-603d-4f67-a19b-8eca9424efdb'), max_length=260),
        ),
    ]
