# Generated by Django 3.0.3 on 2021-02-20 20:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_auto_20210220_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('c23a01e9-ffdd-47b2-9551-3392c842e475'), max_length=260),
        ),
    ]
