# Generated by Django 3.0.3 on 2021-02-20 21:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_auto_20210220_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('1b493804-fd67-40b0-8568-2f971985afc3'), max_length=260),
        ),
    ]
