# Generated by Django 3.0.3 on 2021-03-09 21:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_auto_20210309_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2bc7c7f7-7f79-4800-8312-a32d403831c7'), max_length=260),
        ),
    ]
