# Generated by Django 3.0.3 on 2021-03-09 22:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_auto_20210309_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('7b39faf4-9ec3-4cbd-839f-52d75c72bfd5'), max_length=260),
        ),
    ]
