# Generated by Django 3.0.3 on 2021-03-09 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_auto_20210309_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f3935031-e68f-4d0e-aa05-36ae8598eeb0'), max_length=260),
        ),
    ]
