# Generated by Django 3.0.3 on 2021-03-09 23:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_auto_20210309_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('e98b6e26-3c98-47d6-907d-6ae513ee8933'), max_length=260),
        ),
    ]
