# Generated by Django 3.0.3 on 2021-03-10 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_auto_20210310_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('1ad9d943-b258-4eed-9df7-f8ee8b4cd821'), max_length=260),
        ),
    ]
