# Generated by Django 3.0.3 on 2021-03-10 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_auto_20210310_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('665daf99-a4e3-421f-90e4-338ac62803dc'), max_length=260),
        ),
    ]
