# Generated by Django 3.0.3 on 2021-03-13 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_auto_20210310_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('6ed52976-728d-4718-ba3a-4f12de974f3c'), max_length=260),
        ),
    ]
