# Generated by Django 3.0.3 on 2021-03-13 11:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_auto_20210313_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('33dcabb0-7190-40c6-8955-0e78103de522'), max_length=260),
        ),
    ]
