# Generated by Django 3.0.3 on 2021-03-13 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_auto_20210313_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('24fcd64b-1c89-4cf2-83d3-4d6cbe118efa'), max_length=260),
        ),
    ]
