# Generated by Django 3.0.3 on 2021-03-13 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_auto_20210313_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('1c3db561-b850-4c7c-a493-75769c66912f'), max_length=260),
        ),
    ]
