# Generated by Django 3.0.3 on 2021-03-13 13:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_auto_20210313_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('5a9ea70a-b918-476c-af91-80770d4e31ed'), max_length=260),
        ),
    ]
