# Generated by Django 3.0.3 on 2021-03-13 13:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_auto_20210313_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('40eb83bd-1b3c-4d4d-a0ee-626f629d618a'), max_length=260),
        ),
    ]
