# Generated by Django 3.0.3 on 2021-03-13 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_auto_20210313_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('892f11f2-dbc5-4180-b930-954889cdd5e4'), max_length=260),
        ),
    ]
