# Generated by Django 3.0.3 on 2021-03-13 14:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0073_auto_20210313_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('83c15423-e65e-4a67-8f7e-76e257e1cbce'), max_length=260),
        ),
    ]
