# Generated by Django 3.0.3 on 2021-03-13 16:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_auto_20210313_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f5178224-5ed3-46ea-bf8b-3a428da1c3aa'), max_length=260),
        ),
    ]
