# Generated by Django 3.0.3 on 2021-03-16 20:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_auto_20210313_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('57c09f7b-d847-4a20-8e00-f3b888ca0d76'), max_length=260),
        ),
    ]
