# Generated by Django 3.0.3 on 2021-03-17 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0078_auto_20210316_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('6a6079e9-1a11-4b20-b9f2-79a3b3582170'), max_length=260),
        ),
    ]
