# Generated by Django 3.0.3 on 2021-03-17 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_auto_20210317_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('3dace41b-eb4b-4f76-a173-94a8b6a40114'), max_length=260),
        ),
    ]
