# Generated by Django 3.0.3 on 2021-03-17 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0081_auto_20210317_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('6e0e8e6e-d56d-4580-9b21-d3fab31f30f3'), max_length=260),
        ),
    ]
