# Generated by Django 3.0.3 on 2021-03-17 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_auto_20210317_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2056f917-d6e6-4af9-8d99-6d8791e41f0f'), max_length=260),
        ),
    ]
