# Generated by Django 3.0.3 on 2021-03-17 15:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0084_auto_20210317_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('950dddd8-bde3-425e-b130-9a160f7450fd'), max_length=260),
        ),
    ]
