# Generated by Django 3.0.3 on 2021-03-17 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_auto_20210317_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('68ce4716-ee89-48d7-8b19-6e8303ddf7f4'), max_length=260),
        ),
    ]
