# Generated by Django 3.0.3 on 2021-03-17 15:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0086_auto_20210317_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('1d81c3ec-b1ea-40d9-86c3-ec430c3f1137'), max_length=260),
        ),
    ]
