# Generated by Django 3.0.3 on 2021-03-17 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_auto_20210317_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('b1ed62b7-9e1a-4069-a4be-e19d539f4068'), max_length=260),
        ),
    ]
