# Generated by Django 3.0.3 on 2021-03-17 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0088_auto_20210317_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('a79f682f-8deb-43b9-a802-44c77fe62084'), max_length=260),
        ),
    ]
