# Generated by Django 3.0.3 on 2021-03-17 15:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0089_auto_20210317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('03ae13f3-b231-4dab-b855-3b16df78893d'), max_length=260),
        ),
    ]
