# Generated by Django 3.0.3 on 2021-03-17 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_auto_20210317_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('ab84acaa-417d-4f19-a99e-02b8a48c5156'), max_length=260),
        ),
    ]
