# Generated by Django 3.0.3 on 2021-03-17 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_auto_20210317_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('c93988f2-04d3-48a9-98aa-a868a955b7f1'), max_length=260),
        ),
    ]
