# Generated by Django 3.0.3 on 2021-03-17 15:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_auto_20210317_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('ab41ee02-06ed-49fd-bbfb-852eb4836682'), max_length=260),
        ),
    ]
