# Generated by Django 3.0.3 on 2021-03-17 15:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_auto_20210317_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('cad34c06-9570-46b2-9b90-e15dc889c0ae'), max_length=260),
        ),
    ]
