# Generated by Django 3.0.3 on 2021-03-17 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0094_auto_20210317_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f128bec1-acf5-416b-ba81-3c65ee9fa239'), max_length=260),
        ),
    ]
