# Generated by Django 3.0.3 on 2021-03-17 18:06

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_auto_20210317_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='topic',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('fe812278-e8d4-4f16-982e-26a35a9c0e68'), max_length=260),
        ),
    ]
