# Generated by Django 3.0.3 on 2021-03-17 18:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_auto_20210317_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='plain_text',
            field=models.TextField(db_index=True, default=''),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('26d0a012-f28b-4297-aa0e-6373642834aa'), max_length=260),
        ),
    ]
