# Generated by Django 3.0.3 on 2021-03-17 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0097_auto_20210317_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('8634f6eb-9772-44e4-82a4-84766f7dd694'), max_length=260),
        ),
    ]
