# Generated by Django 3.0.3 on 2021-03-18 17:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_auto_20210317_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('44469891-c563-45ff-9e3e-6e588eafca41'), max_length=260),
        ),
    ]
