# Generated by Django 3.0.3 on 2021-03-19 10:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_auto_20210318_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('137ea1c5-1cb4-492f-a74e-6fbfd4f915a7'), max_length=260),
        ),
    ]
