# Generated by Django 3.0.3 on 2021-03-19 10:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_auto_20210319_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('b915ddae-0416-4fab-ab09-4aa391078746'), max_length=260),
        ),
    ]
