# Generated by Django 3.0.3 on 2021-03-19 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_auto_20210319_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('af46c6f4-07c5-4b75-99c8-87daaf0160f7'), max_length=260),
        ),
    ]
