# Generated by Django 3.0.3 on 2021-03-20 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_auto_20210320_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('f2851b1a-9bb1-4243-a6ed-fb428f76105b'), max_length=260),
        ),
    ]
