# Generated by Django 3.0.3 on 2021-03-20 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_auto_20210320_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2b95e5d6-e194-4342-9e22-26e34590d749'), max_length=260),
        ),
    ]
