# Generated by Django 3.0.3 on 2021-03-20 13:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_auto_20210320_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('cb86ebe5-9d39-44cc-983b-899128e58f66'), max_length=260),
        ),
    ]
