# Generated by Django 3.0.3 on 2021-03-20 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0106_auto_20210320_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('25344b8e-7b79-40d9-b507-2e68ac9c2f7d'), max_length=260),
        ),
    ]
