# Generated by Django 3.0.3 on 2021-03-20 23:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0107_auto_20210320_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('2fa737c6-2bdc-47d6-b7b6-b1b38ac1f074'), max_length=260),
        ),
    ]
