# Generated by Django 3.0.3 on 2021-03-22 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0110_auto_20210322_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('97a63419-65d2-4764-8d0f-9ac399856421'), max_length=260),
        ),
    ]
