# Generated by Django 3.0.3 on 2021-03-22 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0111_auto_20210322_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('7651a4e3-d299-4a30-8e1b-6390ce8f2180'), max_length=260),
        ),
    ]
