# Generated by Django 3.0.3 on 2021-03-22 10:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0112_auto_20210322_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='uid',
            field=models.CharField(default=uuid.UUID('35aa496d-9e9d-4808-8fe0-906254dcc7fb'), max_length=260),
        ),
    ]
