# Generated by Django 3.0.3 on 2020-04-14 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malapropos', '0003_flag_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0005_auto_20200408_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='answer_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='answer_flag', to='malapropos.Flag'),
        ),
        migrations.AddField(
            model_name='answer',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='answer_upvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='question_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='question_flag', to='malapropos.Flag'),
        ),
        migrations.AddField(
            model_name='question',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='question_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
