# Generated by Django 3.0.3 on 2020-04-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20200414_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='body',
            new_name='content',
        ),
    ]
