# Generated by Django 3.0.3 on 2020-04-15 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0008_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='question',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='question_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
