# Generated by Django 3.0.3 on 2021-03-09 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_auto_20210309_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='empty', max_length=150),
            preserve_default=False,
        ),
    ]
