# Generated by Django 3.0.3 on 2021-03-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_answerdownvote_answerhide_answersave_answerupvote_questiondownvote_questionhide_questionsave_questio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersave',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='answersave',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerHide',
        ),
        migrations.DeleteModel(
            name='AnswerSave',
        ),
    ]
