# Generated by Django 3.0.3 on 2021-03-17 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_auto_20210317_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='details',
            new_name='rich_text',
        ),
    ]
