# Generated by Django 3.0.3 on 2021-03-17 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0017_auto_20210317_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='question',
            name='saved',
        ),
        migrations.RemoveField(
            model_name='question',
            name='upvote',
        ),
    ]
