# Generated by Django 3.0.3 on 2021-03-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_auto_20210317_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='plain_text',
            field=models.TextField(default=''),
        ),
    ]
