# Generated by Django 3.0.3 on 2021-03-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_question_plain_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvote',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='voters',
        ),
    ]
