# Generated by Django 3.0.3 on 2021-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_auto_20210317_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='plain_text',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
