# Generated by Django 3.0.3 on 2021-03-20 12:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0021_auto_20210317_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsave',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
