# Generated by Django 3.0.3 on 2020-05-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflectedform',
            name='lexeme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vocab.Lexeme'),
        ),
    ]
