# Generated by Django 3.0.3 on 2020-05-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_inflectedform_lexeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inflectedformimage',
            name='curator_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inflectedformpronunciation',
            name='curator_note',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='curator_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceaudio',
            name='curator_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sentencetranslation',
            name='curator_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
