# Generated by Django 3.0.3 on 2020-05-17 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0005_auto_20200517_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexemePair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curator_note', models.CharField(default='', max_length=255, null=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lexeme_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_pair_1', to='vocab.Lexeme')),
                ('lexeme_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexeme_pair_2', to='vocab.Lexeme')),
            ],
        ),
        migrations.CreateModel(
            name='InflectedFormPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curator_note', models.CharField(default='', max_length=255, null=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inflected_form_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflected_form_pair_1', to='vocab.InflectedForm')),
                ('inflected_form_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflected_form_pair_2', to='vocab.InflectedForm')),
            ],
        ),
    ]
