# Generated by Django 3.0.3 on 2020-05-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vocab', '0007_auto_20200517_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflectedform',
            name='languages',
            field=models.ManyToManyField(to='categories.Language'),
        ),
    ]
