# Generated by Django 3.0.3 on 2020-05-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_inflectedform_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflectedform',
            name='curator_note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='inflectedform',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lexemepronunciation',
            name='curator_note',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
