# Generated by Django 3.0.3 on 2020-05-22 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_auto_20200519_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexeme',
            name='primary_definition',
        ),
    ]
