# Generated by Django 3.0.3 on 2020-05-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vocab', '0010_remove_lexeme_primary_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexeme',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lexeme',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='lexeme',
            name='languages',
            field=models.ManyToManyField(related_name='lexemelanguages', to='categories.Language'),
        ),
    ]
