# Generated by Django 3.0.3 on 2020-05-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0012_remove_lexeme_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inflectedform',
            name='languages',
        ),
    ]
