# Generated by Django 3.0.3 on 2020-05-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('vocab', '0013_remove_inflectedform_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflectedform',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language'),
        ),
    ]
