# Generated by Django 3.0.3 on 2020-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0014_inflectedform_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexemedefinition',
            name='source_citation',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='lexemedefinition',
            name='source_name',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
