# Generated by Django 3.0.3 on 2020-05-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0015_auto_20200524_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='lexemedefinition',
            name='part_of_speech',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
