# Generated by Django 3.0.3 on 2020-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0016_lexemedefinition_part_of_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexemedefinition',
            name='source_citation',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lexemedefinition',
            name='source_name',
            field=models.CharField(default='n/a', max_length=255, null=True),
        ),
    ]
