# Generated by Django 3.0.3 on 2020-05-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0017_auto_20200524_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lexemepronunciation',
            name='curator_note',
        ),
        migrations.AlterField(
            model_name='lexemedefinition',
            name='source_citation',
            field=models.TextField(default='n/a', null=True),
        ),
        migrations.AlterField(
            model_name='lexemepronunciation',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
