# Generated by Django 3.0.3 on 2020-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0018_auto_20200524_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflectedformdefinition',
            name='source_citation',
            field=models.TextField(default='n/a', null=True),
        ),
        migrations.AddField(
            model_name='inflectedformdefinition',
            name='source_name',
            field=models.CharField(default='n/a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lexemepronunciation',
            name='audio_file',
            field=models.FileField(null=True, upload_to='vocab/lexemes/pronunciation/%Y/%m/%d'),
        ),
    ]
