# Generated by Django 3.0.3 on 2020-05-31 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0019_auto_20200527_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='topic',
        ),
    ]
