# Generated by Django 3.0.3 on 2020-05-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0020_remove_sentence_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentenceaudio',
            old_name='audiofile',
            new_name='audio_file',
        ),
    ]
