# Generated by Django 3.0.3 on 2020-06-06 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('vocab', '0021_auto_20200531_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('public', models.BooleanField(default=False)),
                ('side_a_text', models.CharField(default='', max_length=250)),
                ('side_a_image', models.ImageField(upload_to='vocab/customcards/images/%Y/%m/%d')),
                ('side_a_audio', models.FileField(null=True, upload_to='vocab/customcards/audio/%Y/%m/%d')),
                ('side_a_hint', models.CharField(default='', max_length=250)),
                ('side_b_text', models.CharField(default='', max_length=250)),
                ('side_b_image', models.ImageField(upload_to='vocab/customcards/images/%Y/%m/%d')),
                ('side_b_audio', models.FileField(null=True, upload_to='vocab/customcards/audio/%Y/%m/%d')),
                ('side_b_hint', models.CharField(default='', max_length=250)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('side_a_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_card_side_a_language', to='categories.Language')),
                ('side_b_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_card_side_b_language', to='categories.Language')),
            ],
        ),
        migrations.CreateModel(
            name='LexemePairLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('number_correct', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lexeme_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.LexemePair')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCardLearning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('number_correct', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.CustomCard')),
            ],
        ),
        migrations.CreateModel(
            name='CardStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='', max_length=250)),
                ('content', models.TextField(default='')),
                ('public', models.BooleanField(default=False)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('custom_cards', models.ManyToManyField(to='vocab.CustomCard')),
                ('learning_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardstack_learning_language', to='categories.Language')),
                ('lexeme_pairs', models.ManyToManyField(to='vocab.LexemePair')),
                ('native_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardstack_native_language', to='categories.Language')),
                ('topics', models.ManyToManyField(to='categories.TopicTag')),
            ],
        ),
    ]
