# Generated by Django 3.0.3 on 2020-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0022_cardstack_customcard_customcardlearning_lexemepairlearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcard',
            name='side_a_hint',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customcard',
            name='side_a_image',
            field=models.ImageField(null=True, upload_to='vocab/customcards/images/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='customcard',
            name='side_b_hint',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customcard',
            name='side_b_image',
            field=models.ImageField(null=True, upload_to='vocab/customcards/images/%Y/%m/%d'),
        ),
    ]
