# Generated by Django 3.0.3 on 2020-06-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0023_auto_20200606_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardstack',
            old_name='content',
            new_name='description',
        ),
    ]
