# Generated by Django 3.0.3 on 2020-06-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0025_auto_20200606_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstack',
            name='custom_cards',
        ),
    ]
