# Generated by Django 3.0.3 on 2021-01-31 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0026_remove_cardstack_custom_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.CardStack')),
            ],
        ),
    ]
