# Generated by Django 3.0.3 on 2021-01-31 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0027_learningstack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearningStack',
            new_name='FavoriteStack',
        ),
    ]
