# Generated by Django 3.0.3 on 2021-03-20 13:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0028_auto_20210131_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardstack',
            name='topic',
        ),
        migrations.AddField(
            model_name='cardstack',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
