# Generated by Django 3.0.3 on 2021-03-20 13:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0029_auto_20210320_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritestack',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritestack',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='vocab.CardStack'),
        ),
    ]
