# Generated by Django 3.0.3 on 2021-03-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0030_auto_20210320_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritestack',
            old_name='curator',
            new_name='user',
        ),
    ]
