# Generated by Django 3.0.3 on 2021-03-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quoted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='forum.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quoted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
