# Generated by Django 3.0.3 on 2020-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malapropos', '0002_auto_20200413_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='reason',
            field=models.CharField(choices=[('Copyright', 'Copyright'), ('Obscene', 'Obscene'), ('Offensive', 'Offensive')], default='Copyright', max_length=10),
        ),
    ]
