# Generated by Django 3.0.3 on 2020-05-12 20:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='new title', max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('objective', models.CharField(default='new objective', max_length=402)),
                ('skill_level', models.CharField(default='Other', max_length=32)),
                ('lesson_type', models.CharField(default='Other', max_length=64)),
                ('citations', models.CharField(default='', max_length=600, null=True)),
                ('published', models.BooleanField(default=False)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_curator', to=settings.AUTH_USER_MODEL)),
                ('native_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_native_language', to='categories.Language')),
                ('target_language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_target_language', to='categories.Language')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_topic', to='categories.TopicTag')),
            ],
        ),
    ]
