# Generated by Django 3.0.3 on 2020-05-12 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='citations',
            new_name='citation',
        ),
    ]
