# Generated by Django 3.0.3 on 2020-05-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_auto_20200517_1525'),
        ('lessons', '0004_lessonvocabbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonvocabbank',
            name='word_pairs',
            field=models.ManyToManyField(to='vocab.InflectedFormPair'),
        ),
    ]
