# Generated by Django 3.0.3 on 2020-05-23 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_lesson_primary_vocab'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='native_language',
            new_name='source_language',
        ),
    ]
