# Generated by Django 3.0.3 on 2021-03-17 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_savedlesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='lessons.Lesson'),
        ),
    ]
