# Generated by Django 3.0.3 on 2021-03-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_auto_20210317_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='curationdate',
            new_name='curation_date',
        ),
        migrations.RenameField(
            model_name='lessonvocabbank',
            old_name='curationdate',
            new_name='curation_date',
        ),
    ]
