# Generated by Django 3.0.3 on 2021-03-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0014_auto_20210317_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='plain_text',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
