# Generated by Django 3.0.3 on 2021-03-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0016_auto_20210317_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
    ]
