# Generated by Django 3.0.3 on 2021-03-17 15:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0017_remove_lesson_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
