# Generated by Django 3.0.3 on 2020-04-04 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('published', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriber', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='', max_length=305)),
                ('notes', models.CharField(default='', max_length=305)),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('youtubeID', models.CharField(max_length=100)),
                ('thumbURL', models.CharField(max_length=200)),
                ('title', models.CharField(default='', max_length=150)),
                ('length', models.PositiveIntegerField(default=0, editable=False)),
                ('duration', models.PositiveIntegerField(editable=False, null=True)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('primarylanguage', models.ManyToManyField(to='categories.Language')),
                ('topictags', models.ManyToManyField(to='categories.TopicTag')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('published', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator', to=settings.AUTH_USER_MODEL)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='elements.Transcript')),
            ],
        ),
    ]
