# Generated by Django 3.0.3 on 2020-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='object_id',
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='transcripts',
            field=models.ManyToManyField(to='elements.Transcript'),
        ),
    ]
