# Generated by Django 3.0.3 on 2020-04-04 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0002_auto_20200404_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='curator',
            new_name='transcriber',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='curator',
            new_name='translator',
        ),
    ]
