# Generated by Django 3.0.3 on 2020-04-04 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('elements', '0003_auto_20200404_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categories.Language'),
            preserve_default=False,
        ),
    ]
