# Generated by Django 3.0.3 on 2020-04-04 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('elements', '0004_translation_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeelement',
            name='primarylanguage',
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='primarylanguage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language'),
        ),
    ]
