# Generated by Django 3.0.3 on 2020-04-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0005_auto_20200404_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
    ]
