# Generated by Django 3.0.3 on 2020-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0007_translation_targetlanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
