# Generated by Django 3.0.3 on 2020-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0008_transcript_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='slug',
            field=models.SlugField(default='delete', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
