# Generated by Django 3.0.3 on 2020-04-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0009_youtubeelement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='transcripts',
            field=models.ManyToManyField(null=True, to='elements.Transcript'),
        ),
    ]
