# Generated by Django 3.0.3 on 2020-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0010_auto_20200404_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='transcripts',
            field=models.ManyToManyField(editable=False, to='elements.Transcript'),
        ),
    ]
