# Generated by Django 3.0.3 on 2020-04-06 20:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('elements', '0012_auto_20200405_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeelement',
            name='topictags',
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.TopicTag'),
        ),
    ]
