# Generated by Django 3.0.3 on 2020-04-06 20:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0013_auto_20200406_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None),
        ),
    ]
