# Generated by Django 3.0.3 on 2020-04-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0014_auto_20200406_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeelement',
            old_name='primarylanguage',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='youtubeelement',
            old_name='youtubeID',
            new_name='videoid',
        ),
        migrations.RemoveField(
            model_name='youtubeelement',
            name='length',
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='duration',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
