# Generated by Django 3.0.3 on 2020-04-07 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0015_auto_20200406_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='hidden',
            field=models.ManyToManyField(related_name='youtube_hidden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='saved',
            field=models.ManyToManyField(related_name='youtube_saved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_curator', to=settings.AUTH_USER_MODEL),
        ),
    ]
