# Generated by Django 3.0.3 on 2020-04-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0016_auto_20200407_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
