# Generated by Django 3.0.3 on 2020-04-08 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0017_auto_20200407_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='hidden',
            field=models.ManyToManyField(blank=True, related_name='youtube_hidden', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=305),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='youtube_saved', to=settings.AUTH_USER_MODEL),
        ),
    ]
