# Generated by Django 3.0.3 on 2020-04-08 14:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0018_auto_20200408_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
