# Generated by Django 3.0.3 on 2020-04-10 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0019_auto_20200408_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='downvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='youtube_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='upvote',
            field=models.ManyToManyField(blank=True, null=True, related_name='youtube_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
