# Generated by Django 3.0.3 on 2020-04-10 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0020_auto_20200410_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='youtube_downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='youtube_upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
