# Generated by Django 3.0.3 on 2020-04-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malapropos', '0003_flag_reason'),
        ('elements', '0021_auto_20200410_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='youtube_flag', to='malapropos.Flag'),
        ),
    ]
