# Generated by Django 3.0.3 on 2020-04-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0022_youtubeelement_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='purgatory',
            field=models.BooleanField(default=False),
        ),
    ]
