# Generated by Django 3.0.3 on 2020-04-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0023_youtubeelement_purgatory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeelement',
            old_name='purgatory',
            new_name='suspended',
        ),
    ]
