# Generated by Django 3.0.3 on 2020-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0024_auto_20200414_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeelement',
            name='audiofile',
            field=models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='youtubeelement',
            name='mediatype',
            field=models.CharField(default='YouTube', max_length=50),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='thumbURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeelement',
            name='videoid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
