# Generated by Django 3.0.3 on 2020-04-16 11:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('malapropos', '0003_flag_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0027_auto_20200416_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.CharField(default='', max_length=305)),
                ('notes', models.CharField(blank=True, default='', max_length=305)),
                ('audiofile', models.FileField(upload_to='audio_files/%Y/%m/%d')),
                ('thumbnail', models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/%Y/%m/%d')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('views', models.PositiveIntegerField(default=0, editable=False)),
                ('suspended', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_curator', to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(blank=True, related_name='audi_downvoted', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ManyToManyField(blank=True, related_name='audio_flag', to='malapropos.Flag')),
                ('hidden', models.ManyToManyField(blank=True, related_name='audio_hidden', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language')),
                ('saved', models.ManyToManyField(blank=True, related_name='audio_saved', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.TopicTag')),
                ('transcripts', models.ManyToManyField(editable=False, to='elements.Transcript')),
                ('upvote', models.ManyToManyField(blank=True, related_name='audi_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
