# Generated by Django 3.0.3 on 2020-04-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0028_audioelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioelement',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='audioelement',
            name='citation',
            field=models.CharField(default='', max_length=305),
        ),
    ]
