# Generated by Django 3.0.3 on 2020-04-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0029_auto_20200416_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioelement',
            name='tags',
        ),
    ]
