# Generated by Django 3.0.3 on 2020-04-16 21:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0030_remove_audioelement_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioelement',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
