# Generated by Django 3.0.3 on 2020-04-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0033_auto_20200419_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeelement',
            name='transcripts',
            field=models.ManyToManyField(blank=True, related_name='youtube_transcripts', to='elements.Transcript'),
        ),
    ]
