# Generated by Django 3.0.3 on 2020-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0034_auto_20200419_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='translation',
            new_name='translations',
        ),
    ]
