# Generated by Django 3.0.3 on 2020-04-19 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0035_auto_20200419_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='transcriber',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='translator',
        ),
        migrations.AddField(
            model_name='transcript',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcript_curator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translation',
            name='curator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translation_curator', to=settings.AUTH_USER_MODEL),
        ),
    ]
