# Generated by Django 3.0.3 on 2020-04-20 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0038_remove_transcript_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='jsoncontent',
            new_name='content',
        ),
    ]
