# Generated by Django 3.0.3 on 2020-04-22 11:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0039_auto_20200420_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
