# Generated by Django 3.0.3 on 2020-04-28 16:48

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malapropos', '0003_flag_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
        ('elements', '0040_auto_20200422_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextMarkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('published', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textmarkup_curator', to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(blank=True, related_name='markup_downvoted', to=settings.AUTH_USER_MODEL)),
                ('forkparent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='elements.TextMarkup')),
                ('targetlanguage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='markup_target', to='categories.Language')),
                ('upvote', models.ManyToManyField(blank=True, related_name='markup_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
