# Generated by Django 3.0.3 on 2020-04-28 16:55

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('malapropos', '0003_flag_reason'),
        ('categories', '0001_initial'),
        ('elements', '0041_textelement_textmarkup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curationdate', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('rawtext', models.TextField(default='')),
                ('charactercount', models.PositiveIntegerField(default=0)),
                ('purpose', models.CharField(default='', max_length=305)),
                ('citation', models.CharField(default='', max_length=305)),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('suspended', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_curator', to=settings.AUTH_USER_MODEL)),
                ('downvote', models.ManyToManyField(blank=True, related_name='text_downvoted', to=settings.AUTH_USER_MODEL)),
                ('flag', models.ManyToManyField(blank=True, related_name='text_flag', to='malapropos.Flag')),
                ('hidden', models.ManyToManyField(blank=True, related_name='text_hidden', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language')),
                ('saved', models.ManyToManyField(blank=True, related_name='text_saved', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.TopicTag')),
                ('translations', models.ManyToManyField(blank=True, related_name='textelements', to='elements.Translation')),
                ('upvote', models.ManyToManyField(blank=True, related_name='text_upvoted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
