# Generated by Django 3.0.3 on 2020-04-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0042_textelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='textelement',
            name='markups',
            field=models.ManyToManyField(blank=True, related_name='textelements', to='elements.TextMarkup'),
        ),
    ]
