# Generated by Django 3.0.3 on 2021-02-20 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0045_savedaudio_savedtext_savedvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedaudio',
            old_name='lesson',
            new_name='audio_element',
        ),
        migrations.RenameField(
            model_name='savedtext',
            old_name='lesson',
            new_name='text_element',
        ),
        migrations.RenameField(
            model_name='savedvideo',
            old_name='lesson',
            new_name='you_tube_element',
        ),
    ]
