# Generated by Django 3.0.3 on 2021-02-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0046_auto_20210220_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedvideo',
            old_name='you_tube_element',
            new_name='youtube_element',
        ),
    ]
