# Generated by Django 3.0.3 on 2021-03-13 11:40

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0047_auto_20210220_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, null=True, unique=True)),
                ('description', models.CharField(default='', max_length=300)),
                ('citation', models.CharField(default='', max_length=300)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Audio', 'Audio'), ('YouTube', 'YouTube')], default='text', max_length=20)),
                ('suspended', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_curator', to=settings.AUTH_USER_MODEL)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Language')),
            ],
        ),
    ]
