# Generated by Django 3.0.3 on 2021-03-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0049_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='type',
            new_name='sub_type',
        ),
    ]
