# Generated by Django 3.0.3 on 2021-03-13 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0050_auto_20210313_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element')),
                ('audiofile', models.FileField(upload_to='audio_files/%Y/%m/%d')),
                ('originalfilename', models.CharField(default='', max_length=200)),
            ],
            bases=('elements.element',),
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.Element')),
                ('duration', models.PositiveIntegerField(default=0)),
                ('video_id', models.CharField(blank=True, max_length=100, null=True)),
                ('thumbURL', models.CharField(max_length=200)),
            ],
            bases=('elements.element',),
        ),
    ]
