# Generated by Django 3.0.3 on 2021-03-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0051_audio_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
