# Generated by Django 3.0.3 on 2021-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0052_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='video_id',
            field=models.CharField(default='123456abcdef', max_length=100),
            preserve_default=False,
        ),
    ]
