# Generated by Django 3.0.3 on 2021-03-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0054_elementdownvote_elementhide_elementsave_elementupvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementdownvote',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='elements.Element'),
        ),
        migrations.AlterField(
            model_name='elementhide',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hides', to='elements.Element'),
        ),
        migrations.AlterField(
            model_name='elementsave',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='elements.Element'),
        ),
        migrations.AlterField(
            model_name='elementupvote',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='elements.Element'),
        ),
    ]
