# Generated by Django 3.0.3 on 2021-03-13 16:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0056_auto_20210313_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='tags2',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='element',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
