# Generated by Django 3.0.3 on 2021-03-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0057_auto_20210313_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='tags2',
        ),
    ]
