# Generated by Django 3.0.3 on 2021-03-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malapropos', '0003_flag_reason'),
        ('elements', '0058_remove_element_tags2'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='flag',
            field=models.ManyToManyField(blank=True, related_name='elements', to='malapropos.Flag'),
        ),
    ]
