# Generated by Django 3.0.3 on 2021-03-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0059_element_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.CharField(db_index=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='text',
            name='plain_text',
            field=models.TextField(db_index=True, default=''),
        ),
    ]
