# Generated by Django 3.0.3 on 2021-03-17 18:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0060_auto_20210317_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rich_text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('plain_text', models.TextField(default='')),
                ('suspended', models.BooleanField(default=False)),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_comments', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='elements.Element')),
            ],
        ),
    ]
