# Generated by Django 3.0.3 on 2021-03-18 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0061_elementcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcomment',
            name='curator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='element_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
