# Generated by Django 3.0.3 on 2021-03-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0062_auto_20210318_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='thumb',
            field=models.ImageField(default='default.jpg/default_audio.jpg', upload_to='elements/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='text',
            name='thumb',
            field=models.ImageField(default='elements/default_text.jpg', upload_to='elements/%Y/%m/%d'),
        ),
    ]
