# Generated by Django 3.0.3 on 2021-03-19 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0063_auto_20210319_1015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtube',
            old_name='thumbURL',
            new_name='thumb',
        ),
    ]
