# Generated by Django 3.0.3 on 2021-03-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0064_auto_20210319_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='thumb',
            field=models.ImageField(default='elements/default_audio.jpg', upload_to='elements/%Y/%m/%d'),
        ),
    ]
