# Generated by Django 3.0.3 on 2021-03-20 12:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0065_auto_20210319_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementsave',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
