# Generated by Django 3.0.3 on 2021-03-20 23:53

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elements', '0066_elementsave_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curation_date', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('rich_text', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('plain_text', models.TextField(default='')),
                ('suspended', models.BooleanField(default=False)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='elements.ElementComment')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_comment_replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
