# Generated by Django 3.0.3 on 2021-03-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0068_auto_20210322_1012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='curationdate',
            new_name='curation_date',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='content',
            new_name='rich_text',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='curationdate',
            new_name='curation_date',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='targetlanguage',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='content',
            new_name='rich_text',
        ),
    ]
