# Generated by Django 3.0.3 on 2021-03-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elements', '0069_auto_20210322_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='elements.Element'),
        ),
    ]
